using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace omeni
{
    /// <summary>
    /// Interaction logic for skola.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class skola : ContentPage
    {
        public skola()
        {
            InitializeComponent();
        }
    }
}
	